apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2020-04-21T08:32:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: app-10g-pv
  resourceVersion: "122571"
  #selfLink: /api/v1/persistentvolumes/app-10g-pv
  #uid: ab9e8d2d-83aa-11ea-96db-001a4a160119
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  #claimRef:
    #apiVersion: v1
    #kind: PersistentVolumeClaim
    #name: app-mysql
    #namespace: app 
    #resourceVersion: "114491"
    #uid: 0efacd60-83aa-11ea-96db-001a4a160119
  local:
    path: /var/lib/app/mysql/10_2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8snode-2.novalocal
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
